image: "gableroux/unity3d:2018.3.1f1"

stages:
- test
- build


variables:
  BUILD_NAME: ExampleProjectName

.unity_before_script: &unity_before_script
  before_script:
  - cd ./unity/Satellite-Simulator/
  - chmod +x ./ci/before_script.sh && ./ci/before_script.sh

.test: &test
  stage: test
  <<: *unity_before_script
  script:
  - chmod +x ./ci/test.sh && ./ci/test.sh
  artifacts:
    paths:
    - $(pwd)/unity/Satellite-Simulator/$TEST_PLATFORM-results.xml

test-editmode:
  <<: *test
  variables:
    TEST_PLATFORM: editmode

test-playmode:
  <<: *test
  variables:
    TEST_PLATFORM: playmode

.build: &build
  stage: build
  #tip: you can reuse same stage to do everything in parallel and reduce overall time
  #stage: test
  <<: *unity_before_script
  script:
  - chmod +x ./ci/build.sh && ./ci/build.sh

  artifacts:
    paths:
    - $(pwd)/unity/Satellite-Simulator/Builds/
#tip: uncomment following lines if you'd like to build only on master branch
#   only:
#     - master

build-StandaloneWindows64:
  <<: *build
  variables:
    BUILD_TARGET: StandaloneWindows64

